#prettier-ignore
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-hello
  namespace: default
  annotations:
    notifications.argoproj.io/subscribe.on-health-degraded.slack: "true"
    notifications.argoproj.io/subscribe.on-sync-failed.slack: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-hello
  template:
    metadata:
      labels:
        app: nodejs-hello
    spec:
      containers:
        - name: nodejs-hello
          image:  nginx:nonexistent-tag
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-hello-service
  namespace: default
spec:
  selector:
    app: nodejs-hello
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP
